#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/OABRemoteDesk/OABRemoteDesk /usr/bin/OABRemoteDesk

		if [ -e /etc/systemd/system/OABRemoteDesk.service ]; then
			rm /etc/systemd/system/OABRemoteDesk.service /usr/lib/systemd/system/OABRemoteDesk.service /usr/lib/systemd/user/OABRemoteDesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/OABRemoteDesk/files/systemd/OABRemoteDesk.service /usr/lib/systemd/system/OABRemoteDesk.service
		systemctl daemon-reload
		systemctl enable OABRemoteDesk
		systemctl start OABRemoteDesk
	fi
fi
